services:
  hello:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.17.0
    command: >
      mlflow server
      --host 0.0.0.0
      --port 4000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
    volumes:
      - ./_infra/mlflow/mlruns:/mlruns
      - ./_infra/mlflow/db:/mlflowdb
    ports:
      - "4000:4000"
    restart: unless-stopped
volumes:
  mlruns:
